In [ ]:
pip install xgboost

Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (3.2.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.0.2)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.29.7)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost) (1.16.3)

In [ ]:
pip install lightgbm

Requirement already satisfied: lightgbm in /usr/local/lib/python3.12/dist-packages (4.6.0)
Requirement already satisfied: numpy>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from lightgbm) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from lightgbm) (1.16.3)

In [ ]:
pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)
Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 7.8 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.10

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split , GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor

from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/calories.csv')

In [ ]:
df.head(3)

,User_ID,Gender,Age,Height,Weight,Duration,Heart_Rate,Body_Temp,Calories
0,14733363,male,68,190.0,94.0,29.0,105.0,40.8,231.0
1,14861698,female,20,166.0,60.0,14.0,94.0,40.3,66.0
2,11179863,male,69,179.0,79.0,5.0,88.0,38.7,26.0

In [ ]:
df.drop(['User_ID'],axis=1,inplace=True)

In [ ]:
df.head(3)

   Gender  Age  Height  Weight  Duration  Heart_Rate  Body_Temp  Calories
0    male   68   190.0    94.0      29.0       105.0       40.8     231.0
1  female   20   166.0    60.0      14.0        94.0       40.3      66.0
2    male   69   179.0    79.0       5.0        88.0       38.7      26.0

In [ ]:
df.isnull().sum()

Gender        0
Age           0
Height        0
Weight        0
Duration      0
Heart_Rate    0
Body_Temp     0
Calories      0
dtype: int64

In [ ]:
x=df.drop('Calories',axis=1)
y=df['Calories']

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42)

In [ ]:
preprocessor=ColumnTransformer(transformers=[
    ('tnf1',OneHotEncoder(sparse_output=False,drop='first'),['Gender'])
], remainder='passthrough')

In [ ]:
x_train=preprocessor.fit_transform(x_train)

In [ ]:
x_test=preprocessor.transform(x_test)

In [ ]:
pipe_linreg = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LinearRegression())
])
pipe_rfr = Pipeline([
    ('scaler', StandardScaler()),
    ('model', RandomForestRegressor())
])
pipe_xgbr = Pipeline([
    ('scaler', StandardScaler()),
    ('model', XGBRegressor())
])
pipe_lgbmr = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LGBMRegressor())
])
pipe_cbr = Pipeline([
    ('scaler', StandardScaler()),
    ('model', CatBoostRegressor())
])

In [ ]:
model_hyperparameters = {

    pipe_linreg: {},

    pipe_rfr: {
        'model__n_estimators': [50,100],
        'model__max_depth': [None, 10, 20]

    },

    pipe_xgbr: {
        'model__n_estimators': [50,100],
        'model__learning_rate': [0.01, 0.1]
    },

    pipe_lgbmr: {
        'model__n_estimators': [50,100],
        'model__learning_rate': [0.01, 0.1]

    },

    pipe_cbr: {
        'model__iterations': [100],
        'model__learning_rate': [0.05, 0.1]
    }
}

In [ ]:
def ModelSelection(model_hyperparameters, X_train, y_train):
    results = []
    best_model = None
    best_score = -float('inf') # স্কোর নেগেটিভও হতে পারে তাই inf রাখা নিরাপদ

    for model, params in model_hyperparameters.items():
        # scoring='r2' ব্যবহার করা হয়েছে
        grid = GridSearchCV(model, params, cv=3, scoring='r2')
        grid.fit(X_train, y_train)
        score = grid.best_score_

        results.append({
            "model": model,
            "best_score": score,
            "best_params": grid.best_params_
        })

        if score > best_score:
            best_score = score
            best_model = grid.best_estimator_

    results_df = pd.DataFrame(results)
    return results_df, best_model

In [ ]:
results_df, best_model = ModelSelection(model_hyperparameters, x_train, y_train)
print(results_df)

print("Best Model:", best_model)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000627 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 358
[LightGBM] [Info] Number of data points in the train set: 8000, number of used features: 7
[LightGBM] [Info] Start training from score 89.078750
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000207 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 358
[LightGBM] [Info] Number of data points in the train set: 8000, number of used features: 7
[LightGBM] [Info] Start training from score 89.078125
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000631 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 358
[LightGBM] [Info] Number of data points in the train set: 8000, number of used features: 7
[LightGBM] [Info] Start training from score 89.129375

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000582 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 358
[LightGBM] [Info] Number of data points in the train set: 8000, number of used features: 7
[LightGBM] [Info] Start training from score 89.078750
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000585 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 358
[LightGBM] [Info] Number of data points in the train set: 8000, number of used features: 7
[LightGBM] [Info] Start training from score 89.078125

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000639 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 358
[LightGBM] [Info] Number of data points in the train set: 8000, number of used features: 7
[LightGBM] [Info] Start training from score 89.129375
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001053 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 358
[LightGBM] [Info] Number of data points in the train set: 8000, number of used features: 7
[LightGBM] [Info] Start training from score 89.078750

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000590 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 358
[LightGBM] [Info] Number of data points in the train set: 8000, number of used features: 7
[LightGBM] [Info] Start training from score 89.078125
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000601 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 358
[LightGBM] [Info] Number of data points in the train set: 8000, number of used features: 7
[LightGBM] [Info] Start training from score 89.129375
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000194 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 358
[LightGBM] [Info] Number of data points in the train set: 8000, number of used features: 7
[LightGBM] [Info] Start training from score 89.078750

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000594 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 358
[LightGBM] [Info] Number of data points in the train set: 8000, number of used features: 7
[LightGBM] [Info] Start training from score 89.078125
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000861 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 358
[LightGBM] [Info] Number of data points in the train set: 8000, number of used features: 7
[LightGBM] [Info] Start training from score 89.129375

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000877 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 366
[LightGBM] [Info] Number of data points in the train set: 12000, number of used features: 7
[LightGBM] [Info] Start training from score 89.095417
0:	learn: 59.9358037	total: 2.35ms	remaining: 233ms
1:	learn: 57.2404989	total: 4.27ms	remaining: 209ms
2:	learn: 54.7183223	total: 6.14ms	remaining: 199ms
3:	learn: 52.3166374	total: 7.88ms	remaining: 189ms
4:	learn: 49.9793335	total: 9.7ms	remaining: 184ms
5:	learn: 47.8328739	total: 11.4ms	remaining: 179ms
6:	learn: 45.8165925	total: 12.9ms	remaining: 171ms
7:	learn: 43.9168955	total: 14.6ms	remaining: 168ms
8:	learn: 42.0132931	total: 16.4ms	remaining: 166ms
9:	learn: 40.1955787	total: 18.2ms	remaining: 164ms
10:	learn: 38.4767051	total: 19.9ms	remaining: 161ms
11:	learn: 36.8447663	total: 21.6ms	remaining: 158ms
12:	learn: 35.2613550	total: 23.4ms	remaining: 156ms
13:	learn: 33.7894998	total: 25.1ms	remaining: 154ms
14:	learn: 32.3562007	total: 26.8ms	remaining: 152ms
15:	learn: 30.9835671	total: 28.5ms	remaining: 150ms
16:	learn: 29.6486465	total: 30.3ms	remaining: 148ms
17:	learn: 28.4272772	total: 32.1ms	remaining: 146ms
18:	learn: 27.2545115	total: 33.9ms	remaining: 145ms
19:	learn: 26.1659531	total: 35.6ms	remaining: 142ms
20:	learn: 25.0766430	total: 37.3ms	remaining: 140ms
21:	learn: 24.0640716	total: 38.9ms	remaining: 138ms
22:	learn: 23.0861341	total: 40.7ms	remaining: 136ms
23:	learn: 22.1461022	total: 42.3ms	remaining: 134ms
24:	learn: 21.2988761	total: 44ms	remaining: 132ms
25:	learn: 20.4587455	total: 45.8ms	remaining: 130ms
26:	learn: 19.6576488	total: 47.5ms	remaining: 129ms
27:	learn: 18.8866943	total: 49.3ms	remaining: 127ms
28:	learn: 18.1651956	total: 50.9ms	remaining: 125ms
29:	learn: 17.4694483	total: 58.6ms	remaining: 137ms
30:	learn: 16.8143145	total: 64.9ms	remaining: 145ms
31:	learn: 16.1680663	total: 71.5ms	remaining: 152ms
32:	learn: 15.5463165	total: 76.5ms	remaining: 155ms
33:	learn: 14.9747765	total: 80.9ms	remaining: 157ms
34:	learn: 14.4244860	total: 87.4ms	remaining: 162ms
35:	learn: 13.9097700	total: 93.2ms	remaining: 166ms
36:	learn: 13.4001607	total: 99ms	remaining: 169ms
37:	learn: 12.9288996	total: 101ms	remaining: 165ms
38:	learn: 12.4770770	total: 103ms	remaining: 161ms
39:	learn: 12.0298728	total: 105ms	remaining: 157ms
40:	learn: 11.6369066	total: 107ms	remaining: 153ms
41:	learn: 11.2506865	total: 108ms	remaining: 150ms
42:	learn: 10.9063610	total: 110ms	remaining: 146ms
43:	learn: 10.5473953	total: 112ms	remaining: 143ms
44:	learn: 10.2100987	total: 114ms	remaining: 140ms
45:	learn: 9.8880861	total: 116ms	remaining: 136ms
46:	learn: 9.5833819	total: 118ms	remaining: 133ms
47:	learn: 9.2781800	total: 120ms	remaining: 130ms
48:	learn: 9.0007033	total: 122ms	remaining: 127ms
49:	learn: 8.7411645	total: 124ms	remaining: 124ms
50:	learn: 8.4972737	total: 125ms	remaining: 120ms
51:	learn: 8.2517616	total: 127ms	remaining: 117ms
52:	learn: 8.0292444	total: 129ms	remaining: 114ms
53:	learn: 7.8064146	total: 131ms	remaining: 111ms
54:	learn: 7.5968428	total: 133ms	remaining: 109ms
55:	learn: 7.3956224	total: 135ms	remaining: 106ms
56:	learn: 7.1903859	total: 136ms	remaining: 103ms
57:	learn: 7.0105284	total: 138ms	remaining: 100ms
58:	learn: 6.8394184	total: 140ms	remaining: 97.2ms
59:	learn: 6.6642330	total: 142ms	remaining: 94.4ms
60:	learn: 6.4993645	total: 144ms	remaining: 91.8ms
61:	learn: 6.3600885	total: 145ms	remaining: 89.1ms
62:	learn: 6.2208135	total: 147ms	remaining: 86.5ms
63:	learn: 6.0810463	total: 149ms	remaining: 83.8ms
64:	learn: 5.9406164	total: 151ms	remaining: 81.5ms
65:	learn: 5.8176482	total: 153ms	remaining: 79ms
66:	learn: 5.6957967	total: 155ms	remaining: 76.4ms
67:	learn: 5.5779585	total: 157ms	remaining: 73.8ms
68:	learn: 5.4736172	total: 159ms	remaining: 71.2ms
69:	learn: 5.3639283	total: 160ms	remaining: 68.7ms
70:	learn: 5.2610932	total: 162ms	remaining: 66.3ms
71:	learn: 5.1556854	total: 164ms	remaining: 63.8ms
72:	learn: 5.0602506	total: 166ms	remaining: 61.3ms
73:	learn: 4.9746148	total: 168ms	remaining: 58.9ms
74:	learn: 4.8845315	total: 169ms	remaining: 56.5ms
75:	learn: 4.8014231	total: 171ms	remaining: 54ms
76:	learn: 4.7147329	total: 173ms	remaining: 51.6ms
77:	learn: 4.6339539	total: 175ms	remaining: 49.2ms
78:	learn: 4.5623231	total: 176ms	remaining: 46.9ms
79:	learn: 4.4882894	total: 178ms	remaining: 44.5ms
80:	learn: 4.4245616	total: 180ms	remaining: 42.1ms
81:	learn: 4.3591796	total: 181ms	remaining: 39.8ms
82:	learn: 4.3033490	total: 183ms	remaining: 37.5ms
83:	learn: 4.2477046	total: 185ms	remaining: 35.2ms
84:	learn: 4.1874729	total: 186ms	remaining: 32.9ms
85:	learn: 4.1336905	total: 188ms	remaining: 30.6ms
86:	learn: 4.0746241	total: 190ms	remaining: 28.4ms
87:	learn: 4.0278293	total: 192ms	remaining: 26.2ms
88:	learn: 3.9829150	total: 194ms	remaining: 23.9ms
89:	learn: 3.9266679	total: 195ms	remaining: 21.7ms
90:	learn: 3.8842763	total: 197ms	remaining: 19.5ms
91:	learn: 3.8366021	total: 199ms	remaining: 17.3ms
92:	learn: 3.7874714	total: 200ms	remaining: 15.1ms
93:	learn: 3.7491448	total: 202ms	remaining: 12.9ms
94:	learn: 3.7038740	total: 204ms	remaining: 10.7ms
95:	learn: 3.6664223	total: 206ms	remaining: 8.57ms
96:	learn: 3.6230123	total: 208ms	remaining: 6.42ms
97:	learn: 3.5821532	total: 209ms	remaining: 4.27ms
98:	learn: 3.5537633	total: 211ms	remaining: 2.13ms
99:	learn: 3.5148705	total: 213ms	remaining: 0us
0:	learn: 59.0807342	total: 2ms	remaining: 198ms
1:	learn: 56.4557152	total: 4.39ms	remaining: 215ms
2:	learn: 53.9357765	total: 6.29ms	remaining: 204ms
3:	learn: 51.5652352	total: 8.17ms	remaining: 196ms
4:	learn: 49.2891868	total: 10.1ms	remaining: 192ms
5:	learn: 47.1752029	total: 12ms	remaining: 188ms
6:	learn: 45.2152686	total: 13.6ms	remaining: 180ms
7:	learn: 43.3500057	total: 16.5ms	remaining: 190ms
8:	learn: 41.4828393	total: 19.5ms	remaining: 197ms
9:	learn: 39.6462824	total: 21.8ms	remaining: 196ms
10:	learn: 37.9685848	total: 23.6ms	remaining: 191ms
11:	learn: 36.4075557	total: 25.4ms	remaining: 186ms
12:	learn: 34.8586593	total: 27.3ms	remaining: 183ms
13:	learn: 33.4118110	total: 29.1ms	remaining: 179ms
14:	learn: 31.9657140	total: 31ms	remaining: 175ms
15:	learn: 30.6235540	total: 32.8ms	remaining: 172ms
16:	learn: 29.3119867	total: 34.6ms	remaining: 169ms
17:	learn: 28.1612101	total: 36.4ms	remaining: 166ms
18:	learn: 27.0198162	total: 38.1ms	remaining: 163ms
19:	learn: 25.9629793	total: 39.9ms	remaining: 160ms
20:	learn: 24.8786575	total: 42ms	remaining: 158ms
21:	learn: 23.9006241	total: 43.8ms	remaining: 155ms
22:	learn: 22.9044907	total: 45.6ms	remaining: 153ms
23:	learn: 21.9687329	total: 47.5ms	remaining: 151ms
24:	learn: 21.1024435	total: 49.4ms	remaining: 148ms
25:	learn: 20.2679857	total: 51.2ms	remaining: 146ms
26:	learn: 19.4755032	total: 53ms	remaining: 143ms
27:	learn: 18.7177958	total: 54.8ms	remaining: 141ms
28:	learn: 18.0334564	total: 56.6ms	remaining: 139ms
29:	learn: 17.3416153	total: 58.4ms	remaining: 136ms
30:	learn: 16.6587102	total: 60.1ms	remaining: 134ms
31:	learn: 16.0156801	total: 62.5ms	remaining: 133ms
32:	learn: 15.4100665	total: 64.3ms	remaining: 131ms
33:	learn: 14.8463257	total: 66.2ms	remaining: 128ms
34:	learn: 14.2870299	total: 68ms	remaining: 126ms
35:	learn: 13.7721455	total: 69.7ms	remaining: 124ms
36:	learn: 13.2802656	total: 71.5ms	remaining: 122ms
37:	learn: 12.8404295	total: 73.3ms	remaining: 120ms
38:	learn: 12.3768614	total: 75.1ms	remaining: 117ms
39:	learn: 11.9273555	total: 76.9ms	remaining: 115ms
40:	learn: 11.5388313	total: 78.7ms	remaining: 113ms
41:	learn: 11.1577033	total: 80.4ms	remaining: 111ms
42:	learn: 10.8163257	total: 82.1ms	remaining: 109ms
43:	learn: 10.4660622	total: 83.9ms	remaining: 107ms
44:	learn: 10.1180294	total: 85.7ms	remaining: 105ms
45:	learn: 9.8005440	total: 87.5ms	remaining: 103ms
46:	learn: 9.5107002	total: 89.3ms	remaining: 101ms
47:	learn: 9.2243632	total: 91ms	remaining: 98.6ms
48:	learn: 8.9443235	total: 92.8ms	remaining: 96.6ms
49:	learn: 8.6856094	total: 94.6ms	remaining: 94.6ms
50:	learn: 8.4330882	total: 96.3ms	remaining: 92.6ms
51:	learn: 8.1782506	total: 98.1ms	remaining: 90.6ms
52:	learn: 7.9593332	total: 99.9ms	remaining: 88.6ms
53:	learn: 7.7405277	total: 102ms	remaining: 86.6ms
54:	learn: 7.5265772	total: 103ms	remaining: 84.6ms
55:	learn: 7.3297460	total: 105ms	remaining: 82.6ms
56:	learn: 7.1289822	total: 107ms	remaining: 80.6ms
57:	learn: 6.9593899	total: 109ms	remaining: 78.6ms
58:	learn: 6.7829220	total: 110ms	remaining: 76.7ms
59:	learn: 6.6069067	total: 112ms	remaining: 74.8ms
60:	learn: 6.4428421	total: 114ms	remaining: 72.9ms
61:	learn: 6.2978861	total: 116ms	remaining: 71ms
62:	learn: 6.1599962	total: 118ms	remaining: 69.1ms
63:	learn: 6.0316107	total: 119ms	remaining: 67.2ms
64:	learn: 5.8874960	total: 121ms	remaining: 65.2ms
65:	learn: 5.7640409	total: 123ms	remaining: 63.3ms
66:	learn: 5.6330711	total: 125ms	remaining: 61.5ms
67:	learn: 5.5135763	total: 127ms	remaining: 59.6ms
68:	learn: 5.3960748	total: 129ms	remaining: 57.7ms
69:	learn: 5.2853699	total: 130ms	remaining: 55.8ms
70:	learn: 5.1799517	total: 132ms	remaining: 54ms
71:	learn: 5.0676651	total: 134ms	remaining: 52.1ms
72:	learn: 4.9745279	total: 136ms	remaining: 50.2ms
73:	learn: 4.8882322	total: 137ms	remaining: 48.3ms
74:	learn: 4.8003396	total: 139ms	remaining: 46.4ms
75:	learn: 4.7223577	total: 141ms	remaining: 44.4ms
76:	learn: 4.6342743	total: 142ms	remaining: 42.6ms
77:	learn: 4.5465675	total: 144ms	remaining: 40.7ms
78:	learn: 4.4693703	total: 146ms	remaining: 38.8ms
79:	learn: 4.3937668	total: 148ms	remaining: 36.9ms
80:	learn: 4.3199105	total: 149ms	remaining: 35.1ms
81:	learn: 4.2511807	total: 151ms	remaining: 33.2ms
82:	learn: 4.1873468	total: 153ms	remaining: 31.4ms
83:	learn: 4.1279733	total: 155ms	remaining: 29.5ms
84:	learn: 4.0706112	total: 156ms	remaining: 27.6ms
85:	learn: 4.0244130	total: 158ms	remaining: 25.7ms
86:	learn: 3.9696494	total: 160ms	remaining: 23.9ms
87:	learn: 3.9224977	total: 162ms	remaining: 22ms
88:	learn: 3.8774278	total: 163ms	remaining: 20.2ms
89:	learn: 3.8241990	total: 165ms	remaining: 18.3ms
90:	learn: 3.7811573	total: 167ms	remaining: 16.5ms
91:	learn: 3.7384953	total: 169ms	remaining: 14.7ms
92:	learn: 3.6979599	total: 171ms	remaining: 12.9ms
93:	learn: 3.6569987	total: 173ms	remaining: 11ms
94:	learn: 3.6111788	total: 175ms	remaining: 9.2ms
95:	learn: 3.5747368	total: 177ms	remaining: 7.37ms
96:	learn: 3.5300073	total: 179ms	remaining: 5.53ms
97:	learn: 3.4928220	total: 181ms	remaining: 3.7ms
98:	learn: 3.4621381	total: 183ms	remaining: 1.85ms
99:	learn: 3.4263947	total: 186ms	remaining: 0us
0:	learn: 59.3275995	total: 2.12ms	remaining: 210ms
1:	learn: 56.6849678	total: 4.39ms	remaining: 215ms
2:	learn: 54.1568313	total: 8.33ms	remaining: 269ms
3:	learn: 51.7685788	total: 10.3ms	remaining: 248ms
4:	learn: 49.5097777	total: 12.1ms	remaining: 229ms
5:	learn: 47.3844756	total: 13.9ms	remaining: 218ms
6:	learn: 45.4097446	total: 15.6ms	remaining: 207ms
7:	learn: 43.5331924	total: 17.4ms	remaining: 200ms
8:	learn: 41.6564881	total: 19.5ms	remaining: 197ms
9:	learn: 39.8818015	total: 21.3ms	remaining: 192ms
10:	learn: 38.2004074	total: 23.2ms	remaining: 188ms
11:	learn: 36.5676384	total: 25.1ms	remaining: 184ms
12:	learn: 34.9989259	total: 27.1ms	remaining: 181ms
13:	learn: 33.5048490	total: 29ms	remaining: 178ms
14:	learn: 32.0660317	total: 30.7ms	remaining: 174ms
15:	learn: 30.7238855	total: 32.6ms	remaining: 171ms
16:	learn: 29.4010652	total: 34.3ms	remaining: 168ms
17:	learn: 28.2316511	total: 36.2ms	remaining: 165ms
18:	learn: 27.0815042	total: 38ms	remaining: 162ms
19:	learn: 25.9558701	total: 39.9ms	remaining: 160ms
20:	learn: 24.8574465	total: 41.8ms	remaining: 157ms
21:	learn: 23.8403435	total: 43.8ms	remaining: 155ms
22:	learn: 22.9160453	total: 45.7ms	remaining: 153ms
23:	learn: 22.0137842	total: 47.6ms	remaining: 151ms
24:	learn: 21.1484820	total: 49.5ms	remaining: 149ms
25:	learn: 20.3089589	total: 51.3ms	remaining: 146ms
26:	learn: 19.5171539	total: 53.1ms	remaining: 144ms
27:	learn: 18.7608856	total: 54.9ms	remaining: 141ms
28:	learn: 18.0499062	total: 56.8ms	remaining: 139ms
29:	learn: 17.3692888	total: 58.6ms	remaining: 137ms
30:	learn: 16.7029819	total: 60.4ms	remaining: 134ms
31:	learn: 16.0690159	total: 62.4ms	remaining: 133ms
32:	learn: 15.4591093	total: 64.3ms	remaining: 131ms
33:	learn: 14.8838722	total: 66.2ms	remaining: 129ms
34:	learn: 14.3404831	total: 67.9ms	remaining: 126ms
35:	learn: 13.8356988	total: 69.6ms	remaining: 124ms
36:	learn: 13.3479623	total: 71.5ms	remaining: 122ms
37:	learn: 12.9008468	total: 73.5ms	remaining: 120ms
38:	learn: 12.4437935	total: 75.6ms	remaining: 118ms
39:	learn: 11.9939035	total: 77.3ms	remaining: 116ms
40:	learn: 11.6038035	total: 79.1ms	remaining: 114ms
41:	learn: 11.2252858	total: 80.8ms	remaining: 112ms
42:	learn: 10.8842003	total: 82.8ms	remaining: 110ms
43:	learn: 10.5226150	total: 84.5ms	remaining: 108ms
44:	learn: 10.1718422	total: 86.3ms	remaining: 106ms
45:	learn: 9.8442549	total: 88.1ms	remaining: 103ms
46:	learn: 9.5569097	total: 90ms	remaining: 101ms
47:	learn: 9.2626763	total: 91.9ms	remaining: 99.5ms
48:	learn: 8.9657611	total: 93.7ms	remaining: 97.5ms
49:	learn: 8.7068615	total: 95.4ms	remaining: 95.4ms
50:	learn: 8.4558962	total: 97.1ms	remaining: 93.3ms
51:	learn: 8.2031838	total: 98.9ms	remaining: 91.3ms
52:	learn: 7.9900253	total: 101ms	remaining: 89.3ms
53:	learn: 7.7711410	total: 103ms	remaining: 87.3ms
54:	learn: 7.5580245	total: 104ms	remaining: 85.3ms
55:	learn: 7.3614850	total: 106ms	remaining: 83.3ms
56:	learn: 7.1625694	total: 108ms	remaining: 81.5ms
57:	learn: 6.9896102	total: 110ms	remaining: 79.6ms
58:	learn: 6.8201115	total: 112ms	remaining: 77.7ms
59:	learn: 6.6425699	total: 114ms	remaining: 75.9ms
60:	learn: 6.4798586	total: 116ms	remaining: 73.9ms
61:	learn: 6.3238565	total: 117ms	remaining: 71.9ms
62:	learn: 6.1877714	total: 119ms	remaining: 70ms
63:	learn: 6.0582969	total: 121ms	remaining: 68.1ms
64:	learn: 5.9298986	total: 123ms	remaining: 66.3ms
65:	learn: 5.7952646	total: 125ms	remaining: 64.4ms
66:	learn: 5.6684590	total: 127ms	remaining: 62.5ms
67:	learn: 5.5496152	total: 129ms	remaining: 60.5ms
68:	learn: 5.4327902	total: 131ms	remaining: 58.6ms
69:	learn: 5.3197531	total: 132ms	remaining: 56.7ms
70:	learn: 5.2075719	total: 134ms	remaining: 54.7ms
71:	learn: 5.1043814	total: 136ms	remaining: 52.8ms
72:	learn: 5.0042478	total: 138ms	remaining: 50.9ms
73:	learn: 4.9190568	total: 139ms	remaining: 49ms
74:	learn: 4.8333260	total: 141ms	remaining: 47ms
75:	learn: 4.7502285	total: 143ms	remaining: 45.1ms
76:	learn: 4.6649163	total: 145ms	remaining: 43.3ms
77:	learn: 4.5898588	total: 147ms	remaining: 41.4ms
78:	learn: 4.5146648	total: 149ms	remaining: 39.5ms
79:	learn: 4.4516052	total: 151ms	remaining: 37.8ms
80:	learn: 4.3851593	total: 153ms	remaining: 35.9ms
81:	learn: 4.3271108	total: 155ms	remaining: 34ms
82:	learn: 4.2701898	total: 157ms	remaining: 32.2ms
83:	learn: 4.2156238	total: 159ms	remaining: 30.3ms
84:	learn: 4.1482145	total: 161ms	remaining: 28.4ms
85:	learn: 4.0953469	total: 163ms	remaining: 26.5ms
86:	learn: 4.0407363	total: 164ms	remaining: 24.5ms
87:	learn: 3.9851277	total: 166ms	remaining: 22.6ms
88:	learn: 3.9396632	total: 168ms	remaining: 20.7ms
89:	learn: 3.8986725	total: 169ms	remaining: 18.8ms
90:	learn: 3.8403365	total: 171ms	remaining: 16.9ms
91:	learn: 3.7934714	total: 173ms	remaining: 15ms
92:	learn: 3.7417480	total: 175ms	remaining: 13.1ms
93:	learn: 3.7016150	total: 177ms	remaining: 11.3ms
94:	learn: 3.6690826	total: 178ms	remaining: 9.38ms
95:	learn: 3.6349160	total: 180ms	remaining: 7.5ms
96:	learn: 3.5917006	total: 182ms	remaining: 5.62ms
97:	learn: 3.5546647	total: 183ms	remaining: 3.74ms
98:	learn: 3.5232128	total: 185ms	remaining: 1.87ms
99:	learn: 3.4909172	total: 187ms	remaining: 0us
0:	learn: 57.2497212	total: 2.23ms	remaining: 220ms
1:	learn: 52.1239264	total: 4.5ms	remaining: 221ms
2:	learn: 47.4854676	total: 6.5ms	remaining: 210ms
3:	learn: 43.2098001	total: 8.37ms	remaining: 201ms
4:	learn: 39.4577943	total: 10.2ms	remaining: 194ms
5:	learn: 36.1758197	total: 11.9ms	remaining: 186ms
6:	learn: 33.2636740	total: 13.3ms	remaining: 177ms
7:	learn: 30.5475548	total: 15.1ms	remaining: 174ms
8:	learn: 28.0414689	total: 17.2ms	remaining: 173ms
9:	learn: 25.6483093	total: 19ms	remaining: 171ms
10:	learn: 23.6316777	total: 20.8ms	remaining: 168ms
11:	learn: 21.7537053	total: 22.7ms	remaining: 166ms
12:	learn: 20.0432844	total: 24.5ms	remaining: 164ms
13:	learn: 18.5243472	total: 26.3ms	remaining: 162ms
14:	learn: 17.0885273	total: 28.1ms	remaining: 159ms
15:	learn: 15.7429348	total: 30ms	remaining: 158ms
16:	learn: 14.6073919	total: 32ms	remaining: 156ms
17:	learn: 13.6492648	total: 33.8ms	remaining: 154ms
18:	learn: 12.6922934	total: 37.3ms	remaining: 159ms
19:	learn: 11.8089046	total: 40.2ms	remaining: 161ms
20:	learn: 11.0395092	total: 42.5ms	remaining: 160ms
21:	learn: 10.3526563	total: 44.7ms	remaining: 158ms
22:	learn: 9.6887383	total: 46.6ms	remaining: 156ms
23:	learn: 9.1378766	total: 48.4ms	remaining: 153ms
24:	learn: 8.6076141	total: 50.5ms	remaining: 151ms
25:	learn: 8.1348931	total: 52.3ms	remaining: 149ms
26:	learn: 7.6814999	total: 54.5ms	remaining: 147ms
27:	learn: 7.2853667	total: 56.3ms	remaining: 145ms
28:	learn: 6.9348297	total: 58.2ms	remaining: 142ms
29:	learn: 6.5860133	total: 60.2ms	remaining: 140ms
30:	learn: 6.2924079	total: 61.9ms	remaining: 138ms
31:	learn: 6.0008027	total: 63.6ms	remaining: 135ms
32:	learn: 5.7452300	total: 65.4ms	remaining: 133ms
33:	learn: 5.5324249	total: 67.3ms	remaining: 131ms
34:	learn: 5.3096807	total: 69.2ms	remaining: 128ms
35:	learn: 5.1338529	total: 71ms	remaining: 126ms
36:	learn: 4.9606294	total: 72.9ms	remaining: 124ms
37:	learn: 4.8159215	total: 74.9ms	remaining: 122ms
38:	learn: 4.6636728	total: 76.8ms	remaining: 120ms
39:	learn: 4.5246199	total: 78.6ms	remaining: 118ms
40:	learn: 4.4148513	total: 80.3ms	remaining: 116ms
41:	learn: 4.3182973	total: 82.1ms	remaining: 113ms
42:	learn: 4.2244002	total: 83.8ms	remaining: 111ms
43:	learn: 4.1306827	total: 85.7ms	remaining: 109ms
44:	learn: 4.0286381	total: 87.7ms	remaining: 107ms
45:	learn: 3.9385720	total: 89.8ms	remaining: 105ms
46:	learn: 3.8472514	total: 91.9ms	remaining: 104ms
47:	learn: 3.7886251	total: 93.7ms	remaining: 101ms
48:	learn: 3.7203612	total: 95.4ms	remaining: 99.3ms
49:	learn: 3.6443410	total: 97.5ms	remaining: 97.5ms
50:	learn: 3.5880038	total: 99.2ms	remaining: 95.3ms
51:	learn: 3.5455124	total: 101ms	remaining: 93.1ms
52:	learn: 3.4951095	total: 103ms	remaining: 91.1ms
53:	learn: 3.4428643	total: 105ms	remaining: 89ms
54:	learn: 3.3896412	total: 106ms	remaining: 87ms
55:	learn: 3.3280404	total: 108ms	remaining: 85ms
56:	learn: 3.2796217	total: 110ms	remaining: 82.9ms
57:	learn: 3.2255801	total: 112ms	remaining: 80.9ms
58:	learn: 3.1868730	total: 113ms	remaining: 78.8ms
59:	learn: 3.1485908	total: 115ms	remaining: 76.7ms
60:	learn: 3.1200904	total: 117ms	remaining: 74.7ms
61:	learn: 3.0830629	total: 118ms	remaining: 72.6ms
62:	learn: 3.0554703	total: 120ms	remaining: 70.6ms
63:	learn: 3.0185754	total: 122ms	remaining: 68.7ms
64:	learn: 2.9852398	total: 124ms	remaining: 66.7ms
65:	learn: 2.9637481	total: 126ms	remaining: 64.7ms
66:	learn: 2.9404281	total: 127ms	remaining: 62.7ms
67:	learn: 2.9195359	total: 129ms	remaining: 60.7ms
68:	learn: 2.8996149	total: 131ms	remaining: 58.7ms
69:	learn: 2.8680374	total: 132ms	remaining: 56.7ms
70:	learn: 2.8343891	total: 134ms	remaining: 54.8ms
71:	learn: 2.8089349	total: 136ms	remaining: 52.9ms
72:	learn: 2.7938850	total: 138ms	remaining: 50.9ms
73:	learn: 2.7734369	total: 139ms	remaining: 49ms
74:	learn: 2.7494897	total: 141ms	remaining: 47ms
75:	learn: 2.7230623	total: 143ms	remaining: 45.1ms
76:	learn: 2.6979511	total: 145ms	remaining: 43.2ms

In [ ]:
print("Best Model:", best_model)

Best Model: Pipeline(steps=[('scaler', StandardScaler()),
                ('model',
                 XGBRegressor(base_score=None, booster=None, callbacks=None,
                              colsample_bylevel=None, colsample_bynode=None,
                              colsample_bytree=None, device=None,
                              early_stopping_rounds=None,
                              enable_categorical=False, eval_metric=None,
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=0.1,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=None, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=100, n_jobs=None,
                              num_parallel_tree=None, ...))])

In [ ]:
y_pred = best_model.predict(x_test)

In [ ]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

print("R-squared (R2) score:", r2_score(y_test, y_pred))
print("Mean Absolute Error (MAE):", mean_absolute_error(y_test, y_pred))
print("Mean Squared Error (MSE):", mean_squared_error(y_test, y_pred))

R-squared (R2) score: 0.9992399914008103
Mean Absolute Error (MAE): 1.2241583960056306
Mean Squared Error (MSE): 3.0672362273095497

In [ ]:
from sklearn.metrics import r2_score
y_pred = best_model.predict(x_test)
print("Test Set R2 Score:", r2_score(y_test, y_pred))

Test Set R2 Score: 0.9992399914008103

In [ ]:
import pandas as pd
import numpy as np

person_data = {
    'User_ID': [123456],
    'Gender': ['male'],
    'Age': [10],
    'Height': [152.4],
    'Weight': [45.0],
    'Duration': [20.0],
    'Heart_Rate': [110.0],
    'Body_Temp': [40.2]
}


sample_df = pd.DataFrame(person_data)


sample_processed = preprocessor.transform(sample_df.drop(columns=['User_ID']))


predicted_calories = best_model.predict(sample_processed)

print("="*30)
print("   CALORIES PREDICTION RESULT   ")
print("="*30)
print(f"Gender     : {person_data['Gender'][0]}")
print(f"Age        : {person_data['Age'][0]} years")
print(f"Duration   : {person_data['Duration'][0]} minutes")
print(f"Heart Rate : {person_data['Heart_Rate'][0]} bpm")
print("-" * 30)
print(f"Predicted Calories Burned: {predicted_calories[0]:.2f} kcal")
print("="*30)

==============================
   CALORIES PREDICTION RESULT
==============================
Gender     : male
Age        : 10 years
Duration   : 20.0 minutes
Heart Rate : 110.0 bpm
------------------------------
Predicted Calories Burned: 120.85 kcal
==============================