In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

In [ ]:
df= pd.read_csv('data/heart_disease_data.csv')

In [3]:
df.head(5)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [4]:
df['target'].value_counts()

target
1    165
0    138
Name: count, dtype: int64

In [5]:
x=df.drop('target',axis=1)
y= df['target']

In [6]:
models_list = [LogisticRegression(max_iter=10000), SVC(), KNeighborsClassifier(), RandomForestClassifier(random_state=0)]

In [7]:
model_hyperparameters={
    'log_reg':{
        'C':[1,5,10,20]
    },
    'SVC':{
        'kernel':['linear','poly', 'rbf','sigmoid'],
        'C':[1,5,10,20]
    },
    'KNN':{
        'n_neighbors':[3,5,10]
    },
    'random_forest':{
        'n_estimators':[10,20,50,100]
    }
}

In [8]:
model_keys=list(model_hyperparameters.keys())

In [9]:
def ModelSelection(list_of_models, hyperparam_dict):
  result=[]
  i=0
  for model in list_of_models:
    key=model_keys[i]
    param=hyperparam_dict[key]
    i+=1
    classifier=GridSearchCV(model,param,cv=5)
    classifier.fit(x,y)
    result.append({
        'model_used':model,
        'highest_score':classifier.best_score_,
        'best_parameter':classifier.best_params_ # Corrected to best_params_ instead of best_parameter_
    })
  result_dataframe= pd.DataFrame(result,columns=['model_used','highest_score','best_parameter'])
  return result_dataframe

In [10]:
ModelSelection(models_list,model_hyperparameters)

,model_used,highest_score,best_parameter
0,LogisticRegression(max_iter=10000),0.831585,{'C': 5}
1,SVC(),0.828306,"{'C': 1, 'kernel': 'linear'}"
2,KNeighborsClassifier(),0.643880,{'n_neighbors': 5}
3,RandomForestClassifier(random_state=0),0.838087,{'n_estimators': 100}

In [12]:
model_selection_results_df = ModelSelection(models_list, model_hyperparameters)
best_row = model_selection_results_df.loc[model_selection_results_df['highest_score'].idxmax()]
best_model = best_row['model_used']

print("Best Model:", best_model)

Best Model: RandomForestClassifier(random_state=0)